[project]
name = "big-data-pipeline-group4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "pandas>=2.2.3",
    "pyspark>=3.5.3",
    "seaborn>=0.13.2",
]
